### ISSUE TITLE
xcode archive error

### ISSUE THREAD

**Issue by Wanglw2015** [josercc/XCFrameworkBuild#10]
Could not find module 'xxx' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

**Comment by Wanglw2015** [comment]
in swift package manager

**Comment by josercc** [comment]
@Wanglw2015 Can you tell me more about the execution of the command and the computer system version

**Comment by Wanglw2015** [comment]
应该是swift package manager里面使用xcframework只能是动态库的问题
