### ISSUE TITLE
  xcbuild transfer error

### ISSUE THREAD

**Issue by lishuailibertine** [josercc/XCFrameworkBuild#12]
hello,我在用工具把.a 转换为XCFramework的时候出现了: [2]    8012 illegal hardware instruction 这个错误; 我的环境: MAC:10.15.4  Xcode 12.1;

**Comment by josercc** [comment]
可以发一下输入的步骤吗？
需要注意的是 转换对应类型要正确 还有路径不能包含中文

**Comment by lishuailibertine** [comment]
> 可以发一下输入的步骤吗？
> 需要注意的是 转换对应类型要正确 还有路径不能包含中文

 可以在邮箱里发一下您的联系方式吗 weixin什么的？🙏

**Comment by josercc** [comment]
@lishuailibertine 发你邮箱了
