### ISSUE TITLE
What does illegal hardware instruction mean

### ISSUE THREAD

**Issue by boland25** [josercc/XCFrameworkBuild#8]
I tried running the transfer command for a static .a file.  added a path to the .a and a path to the header folder and I get this error in return ` 86762 illegal hardware instruction  xcbuild transfer`.  can you help me understand what that means and how to fix it?

**Comment by josercc** [comment]
What are the steps of the operation can you reply to me, I will try to adjust

**Comment by boland25** [comment]
yes of course, sorry for not providing enough detail.  Here is the command history that I ran...

`xcbuild transfer
1. framework
2. library
Please select the type of conversion 2
Please enter .a file path
lib/Debug/lib.a
Please enter the folder where the header files are located
include
`
And this is the result
`
[1]    12552 illegal hardware instruction  xcbuild transfer
`

**Comment by josercc** [comment]
@boland25 
You need to input the absolute path relative to the computer, but you can't input the relative path.

**Comment by boland25** [comment]
@josercc ok thanks, maybe a line in the readme would be more helpful to others in the future.  thanks for responding!

**Comment by josercc** [comment]
@boland25 Thanks for your suggestion
