### ISSUE TITLE
Failed to build XCFrameworkBuild master with SPM

### ISSUE THREAD

**Issue by Exey** [josercc/XCFrameworkBuild#9]
`mint install josercc/XCFrameworkBuild@master xcbuild -f
🌱 Cloning XCFrameworkBuild master
🌱 Resolving package
🌱 Building package
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Bash.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Command.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Context.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/FileHandle.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Files.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/General/Array.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Process.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Stream/Lazy-split.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Stream/Stream.swift /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/String.swift -supplementary-output-file-map /var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/supplementaryOutputs-24d6c0 -target x86_64-apple-macosx10.15 -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -module-cache-path /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/ModuleCache -swift-version 5 -O -D SWIFT_PACKAGE -target-sdk-version 10.15.6 -parse-as-library -module-name SwiftShell -num-threads 4 -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Bash.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Command.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Context.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/FileHandle.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Files.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/General/Array.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Process.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Stream/Lazy-split.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/Stream/Stream.swift.o -o /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/x86_64-apple-macosx/release/SwiftShell.build/String.swift.o 
1.	Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
2.	While evaluating request TypeCheckSourceFileRequest(source_file "/private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Stream/Stream.swift")
3.	While type-checking 'FileHandleStream' (at /private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Stream/Stream.swift:207:8)
4.	While type-checking protocol conformance to 'TextOutputStreamable' (in module 'Swift') for type 'FileHandleStream' (declared at [/private/var/folders/f5/c9drybn16bq8wzqxkfw60zh80000gn/T/mint/github.com_josercc_XCFrameworkBuild/.build/checkouts/SwiftShell/Sources/SwiftShell/Stream/Stream.swift:207:8 - line:215:1] RangeText="class FileHandleStream: ReadableStream, WritableStream {
	public let filehandle: FileHandle
	public var encoding: String.Encoding

	public init(_ filehandle: FileHandle, encoding: String.Encoding) {
		self.filehandle = filehandle
		self.encoding = encoding
	}
")
0  swift                    0x000000010ee0f865 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift                    0x000000010ee0e865 llvm::sys::RunSignalHandlers() + 85
2  swift                    0x000000010ee0fe1f SignalHandler(int) + 111
3  libsystem_platform.dylib 0x00007fff73dbc5fd _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603338572380704
5  swift                    0x000000010b6b612b swift::constraints::ConstraintSystem::simplifyRestrictedConstraint(swift::constraints::ConversionRestrictionKind, swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 779
6  swift                    0x000000010b6a5cb0 swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 14960
7  swift                    0x000000010b6b0ef1 swift::constraints::ConstraintSystem::repairFailures(swift::Type, swift::Type, swift::constraints::ConstraintKind, llvm::SmallVectorImpl<swift::constraints::RestrictionOrFix>&, swift::constraints::ConstraintLocatorBuilder) + 12529
8  swift                    0x000000010b6a5c45 swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 14853
9  swift                    0x000000010b6a6069 swift::constraints::ConstraintSystem::matchTypes(swift::Type, swift::Type, swift::constraints::ConstraintKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 15913
10 swift                    0x000000010b6caad0 swift::constraints::ConstraintSystem::addConstraintImpl(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder, bool) + 96
11 swift                    0x000000010b6a1b72 swift::constraints::ConstraintSystem::addConstraint(swift::constraints::ConstraintKind, swift::Type, swift::Type, swift::constraints::ConstraintLocatorBuilder, bool) + 66
12 swift                    0x000000010b8d29ed llvm::Optional<swift::RequirementMatch> llvm::function_ref<llvm::Optional<swift::RequirementMatch> (swift::Type, swift::Type)>::callback_fn<swift::matchWitness(llvm::DenseMap<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*>, swift::RequirementEnvironment, llvm::DenseMapInfo<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*> >, llvm::detail::DenseMapPair<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*>, swift::RequirementEnvironment> >&, swift::ProtocolDecl*, swift::ProtocolConformance*, swift::DeclContext*, swift::ValueDecl*, swift::ValueDecl*)::$_1>(long, swift::Type, swift::Type) + 93
13 swift                    0x000000010b8b3dfa swift::matchWitness(swift::DeclContext*, swift::ValueDecl*, swift::ValueDecl*, llvm::function_ref<std::__1::tuple<llvm::Optional<swift::RequirementMatch>, swift::Type, swift::Type> ()>, llvm::function_ref<llvm::Optional<swift::RequirementMatch> (swift::Type, swift::Type)>, llvm::function_ref<swift::RequirementMatch (bool, llvm::ArrayRef<swift::OptionalAdjustment>)>) + 8778
14 swift                    0x000000010b8b5933 swift::matchWitness(llvm::DenseMap<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*>, swift::RequirementEnvironment, llvm::DenseMapInfo<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*> >, llvm::detail::DenseMapPair<std::__1::pair<swift::GenericSignatureImpl const*, swift::ClassDecl const*>, swift::RequirementEnvironment> >&, swift::ProtocolDecl*, swift::ProtocolConformance*, swift::DeclContext*, swift::ValueDecl*, swift::ValueDecl*) + 1187
15 swift                    0x000000010b8b6482 swift::WitnessChecker::findBestWitness(swift::ValueDecl*, bool*, swift::NormalProtocolConformance*, llvm::SmallVectorImpl<swift::RequirementMatch>&, unsigned int&, unsigned int&, bool&) + 946
16 swift                    0x000000010b8c0af3 swift::ConformanceChecker::resolveWitnessViaLookup(swift::ValueDecl*) + 643
17 swift                    0x000000010b8bb9d5 swift::MultiConformanceChecker::checkIndividualConformance(swift::NormalProtocolConformance*, bool) + 14773
18 swift                    0x000000010b8b7ac3 swift::MultiConformanceChecker::checkAllConformances() + 147
19 swift                    0x000000010b8c7647 swift::TypeChecker::checkConformancesInContext(swift::DeclContext*, swift::IterableDeclContext*) + 8295
20 swift                    0x000000010b8778ca (anonymous namespace)::DeclChecker::visitClassDecl(swift::ClassDecl*) + 8138
21 swift                    0x000000010b86fdc3 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 2739
22 swift                    0x000000010b937651 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 753
23 swift                    0x000000010b93a4d9 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 953
24 swift                    0x000000010b9371d4 swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 164
25 swift                    0x000000010aab2858 swift::CompilerInstance::performSemaUpTo(swift::SourceFile::ASTStage_t) + 7576
26 swift                    0x000000010a97332d swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6845
27 swift                    0x000000010a8f7c37 main + 1255
28 libdyld.dylib            0x00007fff73bc3cc9 start + 1
🌱 Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.15". Use --verbose to see full output`

**Comment by josercc** [comment]
@Exey  It has been modified. Please try again
